<?php
/**
 * APIDateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SternerStuff\InsightlyPHP;

/**
 * APIDateTest Class Doc Comment
 *
 * @category    Class
 * @description APIDate
 * @package     SternerStuff\InsightlyPHP
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class APIDateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "APIDate"
     */
    public function testAPIDate()
    {
    }

    /**
     * Test attribute "date_id"
     */
    public function testPropertyDateId()
    {
    }

    /**
     * Test attribute "occasion_name"
     */
    public function testPropertyOccasionName()
    {
    }

    /**
     * Test attribute "occasion_date"
     */
    public function testPropertyOccasionDate()
    {
    }

    /**
     * Test attribute "repeat_yearly"
     */
    public function testPropertyRepeatYearly()
    {
    }

    /**
     * Test attribute "create_task_yearly"
     */
    public function testPropertyCreateTaskYearly()
    {
    }
}
