<?php
/**
 * APIEmailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SternerStuff\InsightlyPHP;

/**
 * APIEmailTest Class Doc Comment
 *
 * @category    Class
 * @description APIEmail
 * @package     SternerStuff\InsightlyPHP
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class APIEmailTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "APIEmail"
     */
    public function testAPIEmail()
    {
    }

    /**
     * Test attribute "email_id"
     */
    public function testPropertyEmailId()
    {
    }

    /**
     * Test attribute "email_from"
     */
    public function testPropertyEmailFrom()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "email_date_utc"
     */
    public function testPropertyEmailDateUtc()
    {
    }

    /**
     * Test attribute "format"
     */
    public function testPropertyFormat()
    {
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }

    /**
     * Test attribute "owner_user_id"
     */
    public function testPropertyOwnerUserId()
    {
    }

    /**
     * Test attribute "date_created_utc"
     */
    public function testPropertyDateCreatedUtc()
    {
    }

    /**
     * Test attribute "queued_send_date_utc"
     */
    public function testPropertyQueuedSendDateUtc()
    {
    }

    /**
     * Test attribute "created_user_id"
     */
    public function testPropertyCreatedUserId()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {
    }
}
