<?php
/**
 * APILeadSourceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SternerStuff\InsightlyPHP;

/**
 * APILeadSourceTest Class Doc Comment
 *
 * @category    Class
 * @description APILeadSource
 * @package     SternerStuff\InsightlyPHP
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class APILeadSourceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "APILeadSource"
     */
    public function testAPILeadSource()
    {
    }

    /**
     * Test attribute "lead_source_id"
     */
    public function testPropertyLeadSourceId()
    {
    }

    /**
     * Test attribute "lead_source"
     */
    public function testPropertyLeadSource()
    {
    }

    /**
     * Test attribute "default_value"
     */
    public function testPropertyDefaultValue()
    {
    }

    /**
     * Test attribute "field_order"
     */
    public function testPropertyFieldOrder()
    {
    }
}
