<?php
/**
 * APIOpportunityStateReasonTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SternerStuff\InsightlyPHP;

/**
 * APIOpportunityStateReasonTest Class Doc Comment
 *
 * @category    Class
 * @description APIOpportunityStateReason
 * @package     SternerStuff\InsightlyPHP
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class APIOpportunityStateReasonTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "APIOpportunityStateReason"
     */
    public function testAPIOpportunityStateReason()
    {
    }

    /**
     * Test attribute "state_reason_id"
     */
    public function testPropertyStateReasonId()
    {
    }

    /**
     * Test attribute "state_reason"
     */
    public function testPropertyStateReason()
    {
    }

    /**
     * Test attribute "for_opportunity_state"
     */
    public function testPropertyForOpportunityState()
    {
    }
}
