<?php
/**
 * APIPricebookEntryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SternerStuff\InsightlyPHP;

/**
 * APIPricebookEntryTest Class Doc Comment
 *
 * @category    Class
 * @description APIPricebookEntry
 * @package     SternerStuff\InsightlyPHP
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class APIPricebookEntryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "APIPricebookEntry"
     */
    public function testAPIPricebookEntry()
    {
    }

    /**
     * Test attribute "pricebook_entry_id"
     */
    public function testPropertyPricebookEntryId()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "use_standard_price"
     */
    public function testPropertyUseStandardPrice()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "created_user_id"
     */
    public function testPropertyCreatedUserId()
    {
    }

    /**
     * Test attribute "date_created_utc"
     */
    public function testPropertyDateCreatedUtc()
    {
    }

    /**
     * Test attribute "date_updated_utc"
     */
    public function testPropertyDateUpdatedUtc()
    {
    }

    /**
     * Test attribute "customfields"
     */
    public function testPropertyCustomfields()
    {
    }
}
