<?php
/**
 * APIQuotationLineItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SternerStuff\InsightlyPHP;

/**
 * APIQuotationLineItemTest Class Doc Comment
 *
 * @category    Class
 * @description APIQuotationLineItem
 * @package     SternerStuff\InsightlyPHP
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class APIQuotationLineItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "APIQuotationLineItem"
     */
    public function testAPIQuotationLineItem()
    {
    }

    /**
     * Test attribute "quotation_item_id"
     */
    public function testPropertyQuotationItemId()
    {
    }

    /**
     * Test attribute "opportunity_item_id"
     */
    public function testPropertyOpportunityItemId()
    {
    }

    /**
     * Test attribute "pricebook_entry_id"
     */
    public function testPropertyPricebookEntryId()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "list_price"
     */
    public function testPropertyListPrice()
    {
    }

    /**
     * Test attribute "unit_price"
     */
    public function testPropertyUnitPrice()
    {
    }

    /**
     * Test attribute "subtotal"
     */
    public function testPropertySubtotal()
    {
    }

    /**
     * Test attribute "discount"
     */
    public function testPropertyDiscount()
    {
    }

    /**
     * Test attribute "total_price"
     */
    public function testPropertyTotalPrice()
    {
    }

    /**
     * Test attribute "date_created_utc"
     */
    public function testPropertyDateCreatedUtc()
    {
    }

    /**
     * Test attribute "date_updated_utc"
     */
    public function testPropertyDateUpdatedUtc()
    {
    }

    /**
     * Test attribute "sort_order"
     */
    public function testPropertySortOrder()
    {
    }

    /**
     * Test attribute "customfields"
     */
    public function testPropertyCustomfields()
    {
    }
}
