<?php
/**
 * APITaskTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SternerStuff\InsightlyPHP;

/**
 * APITaskTest Class Doc Comment
 *
 * @category    Class
 * @description APITask
 * @package     SternerStuff\InsightlyPHP
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class APITaskTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "APITask"
     */
    public function testAPITask()
    {
    }

    /**
     * Test attribute "task_id"
     */
    public function testPropertyTaskId()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "category_id"
     */
    public function testPropertyCategoryId()
    {
    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "completed"
     */
    public function testPropertyCompleted()
    {
    }

    /**
     * Test attribute "details"
     */
    public function testPropertyDetails()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {
    }

    /**
     * Test attribute "percent_complete"
     */
    public function testPropertyPercentComplete()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "milestone_id"
     */
    public function testPropertyMilestoneId()
    {
    }

    /**
     * Test attribute "responsible_user_id"
     */
    public function testPropertyResponsibleUserId()
    {
    }

    /**
     * Test attribute "owner_user_id"
     */
    public function testPropertyOwnerUserId()
    {
    }

    /**
     * Test attribute "email_id"
     */
    public function testPropertyEmailId()
    {
    }

    /**
     * Test attribute "project_id"
     */
    public function testPropertyProjectId()
    {
    }

    /**
     * Test attribute "reminder_date_utc"
     */
    public function testPropertyReminderDateUtc()
    {
    }

    /**
     * Test attribute "owner_visible"
     */
    public function testPropertyOwnerVisible()
    {
    }

    /**
     * Test attribute "parent_task_id"
     */
    public function testPropertyParentTaskId()
    {
    }

    /**
     * Test attribute "recurrence"
     */
    public function testPropertyRecurrence()
    {
    }

    /**
     * Test attribute "opportunity_id"
     */
    public function testPropertyOpportunityId()
    {
    }

    /**
     * Test attribute "assigned_team_id"
     */
    public function testPropertyAssignedTeamId()
    {
    }

    /**
     * Test attribute "customfields"
     */
    public function testPropertyCustomfields()
    {
    }
}
