<?php
/**
 * CustomFieldsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SternerStuff\InsightlyPHP;

use \SternerStuff\InsightlyPHP\Configuration;
use \SternerStuff\InsightlyPHP\ApiException;
use \SternerStuff\InsightlyPHP\ObjectSerializer;

/**
 * CustomFieldsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomFieldsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getCustomFields
     *
     * Gets a list of Custom Fields.
     *
     */
    public function testGetCustomFields()
    {
    }

    /**
     * Test case for getCustomfieldBySearch
     *
     * Gets a Custom Field by name.
     *
     */
    public function testGetCustomfieldBySearch()
    {
    }
}
