<?php
/**
 * OrganisationsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SternerStuff\InsightlyPHP;

use \SternerStuff\InsightlyPHP\Configuration;
use \SternerStuff\InsightlyPHP\ApiException;
use \SternerStuff\InsightlyPHP\ObjectSerializer;

/**
 * OrganisationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrganisationsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addActivitySetAssignment
     *
     * Adds an Activity Set to an Organisation.
     *
     */
    public function testAddActivitySetAssignment()
    {
    }

    /**
     * Test case for addEntity
     *
     * Adds an Organisation.
     *
     */
    public function testAddEntity()
    {
    }

    /**
     * Test case for addFileAttachment
     *
     * Adds a File Attachment to an Organisation.
     *
     */
    public function testAddFileAttachment()
    {
    }

    /**
     * Test case for addFollow
     *
     * Start following an Organisation.
     *
     */
    public function testAddFollow()
    {
    }

    /**
     * Test case for addLink
     *
     * Adds a Link.
     *
     */
    public function testAddLink()
    {
    }

    /**
     * Test case for addNotes
     *
     * Adds a Note to an Organisation.
     *
     */
    public function testAddNotes()
    {
    }

    /**
     * Test case for addTag
     *
     * Adds a Tag to an Organisation.
     *
     */
    public function testAddTag()
    {
    }

    /**
     * Test case for deleteEntity
     *
     * Deletes an Organisation.
     *
     */
    public function testDeleteEntity()
    {
    }

    /**
     * Test case for deleteFollow
     *
     * Stop following an Organisation.
     *
     */
    public function testDeleteFollow()
    {
    }

    /**
     * Test case for deleteImage
     *
     * Deletes an Organisation's Image.
     *
     */
    public function testDeleteImage()
    {
    }

    /**
     * Test case for deleteImageField
     *
     * Deletes an Organisation's Custom Image Field.
     *
     */
    public function testDeleteImageField()
    {
    }

    /**
     * Test case for deleteLink
     *
     * Deletes a Link.
     *
     */
    public function testDeleteLink()
    {
    }

    /**
     * Test case for deleteTag
     *
     * Deletes a Tag from an Organisation.
     *
     */
    public function testDeleteTag()
    {
    }

    /**
     * Test case for getDates
     *
     * Gets an Organisation's Dates.
     *
     */
    public function testGetDates()
    {
    }

    /**
     * Test case for getEmailDomains
     *
     * Gets an Organisation's Email Domains.
     *
     */
    public function testGetEmailDomains()
    {
    }

    /**
     * Test case for getEmails
     *
     * Gets a list of an Organisation's Emails.
     *
     */
    public function testGetEmails()
    {
    }

    /**
     * Test case for getEntities
     *
     * Gets a list of Organisations.
     *
     */
    public function testGetEntities()
    {
    }

    /**
     * Test case for getEntitiesBySearch
     *
     * Gets a filtered list of Organisations.
     *
     */
    public function testGetEntitiesBySearch()
    {
    }

    /**
     * Test case for getEntitiesByTag
     *
     * Gets a list of Organisations filtered by tags.
     *
     */
    public function testGetEntitiesByTag()
    {
    }

    /**
     * Test case for getEntity
     *
     * Gets an Organisation.
     *
     */
    public function testGetEntity()
    {
    }

    /**
     * Test case for getEvents
     *
     * Gets an Organisation's Events.
     *
     */
    public function testGetEvents()
    {
    }

    /**
     * Test case for getFileAttachments
     *
     * Gets an Organisation's File Attachments.
     *
     */
    public function testGetFileAttachments()
    {
    }

    /**
     * Test case for getFollow
     *
     * Gets a Follow state for an Organisation.
     *
     */
    public function testGetFollow()
    {
    }

    /**
     * Test case for getImage
     *
     * Gets an Organisation's Image.
     *
     */
    public function testGetImage()
    {
    }

    /**
     * Test case for getImageField
     *
     * Gets an Organisation's Custom Image Field.
     *
     */
    public function testGetImageField()
    {
    }

    /**
     * Test case for getLinks
     *
     * Gets an Organisation's Links.
     *
     */
    public function testGetLinks()
    {
    }

    /**
     * Test case for getNotes
     *
     * Gets an Organisation's Notes.
     *
     */
    public function testGetNotes()
    {
    }

    /**
     * Test case for getTags
     *
     * Gets an Organisation's Tags.
     *
     */
    public function testGetTags()
    {
    }

    /**
     * Test case for getTasks
     *
     * Gets a list of an Organisation's Tasks.
     *
     */
    public function testGetTasks()
    {
    }

    /**
     * Test case for updateDates
     *
     * Updates an Organisation's Dates.
     *
     */
    public function testUpdateDates()
    {
    }

    /**
     * Test case for updateEmailDomains
     *
     * Updates an Organisation's Email Domains.
     *
     */
    public function testUpdateEmailDomains()
    {
    }

    /**
     * Test case for updateEntity
     *
     * Updates an Organisation.
     *
     */
    public function testUpdateEntity()
    {
    }

    /**
     * Test case for updateImage
     *
     * Updates an Organisation's Image.
     *
     */
    public function testUpdateImage()
    {
    }

    /**
     * Test case for updateImageField
     *
     * Updates an Organisation's Custom Image Field.
     *
     */
    public function testUpdateImageField()
    {
    }

    /**
     * Test case for updateLink
     *
     * Updates a Link.
     *
     */
    public function testUpdateLink()
    {
    }

    /**
     * Test case for updateNotes
     *
     * Updates a note of an Organisation.
     *
     */
    public function testUpdateNotes()
    {
    }

    /**
     * Test case for updateTags
     *
     * Updates an Organisation's Tags.
     *
     */
    public function testUpdateTags()
    {
    }
}
