<?php
/**
 * PriceBooksApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SternerStuff\InsightlyPHP;

use \SternerStuff\InsightlyPHP\Configuration;
use \SternerStuff\InsightlyPHP\ApiException;
use \SternerStuff\InsightlyPHP\ObjectSerializer;

/**
 * PriceBooksApiTest Class Doc Comment
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PriceBooksApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addChildEntity
     *
     * Adds a Price Book Entry to a Price Book.
     *
     */
    public function testAddChildEntity()
    {
    }

    /**
     * Test case for addEntity
     *
     * Adds a Price Book.
     *
     */
    public function testAddEntity()
    {
    }

    /**
     * Test case for addFollow
     *
     * Start following a Price Book.
     *
     */
    public function testAddFollow()
    {
    }

    /**
     * Test case for deleteChildEntity
     *
     * Deletes a Price Book Entry of a Price Book.
     *
     */
    public function testDeleteChildEntity()
    {
    }

    /**
     * Test case for deleteFollow
     *
     * Stop following a Price Book.
     *
     */
    public function testDeleteFollow()
    {
    }

    /**
     * Test case for getChildEntities
     *
     * Gets a list of Price Book Entries of a Price Book.
     *
     */
    public function testGetChildEntities()
    {
    }

    /**
     * Test case for getEntities
     *
     * Gets a list of Price Books.
     *
     */
    public function testGetEntities()
    {
    }

    /**
     * Test case for getEntitiesBySearch
     *
     * Gets a filtered list of Price Books.
     *
     */
    public function testGetEntitiesBySearch()
    {
    }

    /**
     * Test case for getEntity
     *
     * Gets a Price Book.
     *
     */
    public function testGetEntity()
    {
    }

    /**
     * Test case for getFollow
     *
     * Gets a Follow state for a Price Book.
     *
     */
    public function testGetFollow()
    {
    }

    /**
     * Test case for updateChildEntity
     *
     * Updates a Price Book Entry of a Price Book.
     *
     */
    public function testUpdateChildEntity()
    {
    }

    /**
     * Test case for updateEntity
     *
     * Updates a Price Book.
     *
     */
    public function testUpdateEntity()
    {
    }
}
