<?php
/**
 * ProductsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SternerStuff\InsightlyPHP;

use \SternerStuff\InsightlyPHP\Configuration;
use \SternerStuff\InsightlyPHP\ApiException;
use \SternerStuff\InsightlyPHP\ObjectSerializer;

/**
 * ProductsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addChildEntity
     *
     * Adds a Price Book Entry to a Product.
     *
     */
    public function testAddChildEntity()
    {
    }

    /**
     * Test case for addEntity
     *
     * Adds a Product.
     *
     */
    public function testAddEntity()
    {
    }

    /**
     * Test case for addFollow
     *
     * Start following a Product.
     *
     */
    public function testAddFollow()
    {
    }

    /**
     * Test case for deleteChildEntity
     *
     * Deletes a Price Book Entry of a Product.
     *
     */
    public function testDeleteChildEntity()
    {
    }

    /**
     * Test case for deleteEntity
     *
     * Deletes a Product.
     *
     */
    public function testDeleteEntity()
    {
    }

    /**
     * Test case for deleteFollow
     *
     * Stop following a Product.
     *
     */
    public function testDeleteFollow()
    {
    }

    /**
     * Test case for deleteImage
     *
     * Deletes a Product's Image.
     *
     */
    public function testDeleteImage()
    {
    }

    /**
     * Test case for deleteImageField
     *
     * Deletes a Product's Custom Image Field.
     *
     */
    public function testDeleteImageField()
    {
    }

    /**
     * Test case for getChildEntities
     *
     * Gets a list of Price Book Entries of a Product.
     *
     */
    public function testGetChildEntities()
    {
    }

    /**
     * Test case for getEntities
     *
     * Gets a list of Products.
     *
     */
    public function testGetEntities()
    {
    }

    /**
     * Test case for getEntitiesBySearch
     *
     * Gets a filtered list of Products.
     *
     */
    public function testGetEntitiesBySearch()
    {
    }

    /**
     * Test case for getEntity
     *
     * Gets a Product.
     *
     */
    public function testGetEntity()
    {
    }

    /**
     * Test case for getFollow
     *
     * Gets a Follow state for a Product.
     *
     */
    public function testGetFollow()
    {
    }

    /**
     * Test case for getImage
     *
     * Gets a Product's Image.
     *
     */
    public function testGetImage()
    {
    }

    /**
     * Test case for getImageField
     *
     * Gets a Product's Custom Image Field.
     *
     */
    public function testGetImageField()
    {
    }

    /**
     * Test case for updateChildEntity
     *
     * Updates a Price Book Entry of a Product.
     *
     */
    public function testUpdateChildEntity()
    {
    }

    /**
     * Test case for updateEntity
     *
     * Updates a Product.
     *
     */
    public function testUpdateEntity()
    {
    }

    /**
     * Test case for updateImage
     *
     * Updates a Product's Image.
     *
     */
    public function testUpdateImage()
    {
    }

    /**
     * Test case for updateImageField
     *
     * Updates a Product's Custom Image Field.
     *
     */
    public function testUpdateImageField()
    {
    }
}
