<?php
/**
 * ProjectCategoriesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SternerStuff\InsightlyPHP;

use \SternerStuff\InsightlyPHP\Configuration;
use \SternerStuff\InsightlyPHP\ApiException;
use \SternerStuff\InsightlyPHP\ObjectSerializer;

/**
 * ProjectCategoriesApiTest Class Doc Comment
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProjectCategoriesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addProjectCategory
     *
     * Adds a Project Category.
     *
     */
    public function testAddProjectCategory()
    {
    }

    /**
     * Test case for deleteProjectCategory
     *
     * Deactivates a Project Category.
     *
     */
    public function testDeleteProjectCategory()
    {
    }

    /**
     * Test case for getProjectCategories
     *
     * Gets a list of Project Categories.
     *
     */
    public function testGetProjectCategories()
    {
    }

    /**
     * Test case for getProjectCategory
     *
     * Gets a Project Category.
     *
     */
    public function testGetProjectCategory()
    {
    }

    /**
     * Test case for updateProjectCategory
     *
     * Updates a Project Category.
     *
     */
    public function testUpdateProjectCategory()
    {
    }
}
