<?php
/**
 * ProjectsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SternerStuff\InsightlyPHP;

use \SternerStuff\InsightlyPHP\Configuration;
use \SternerStuff\InsightlyPHP\ApiException;
use \SternerStuff\InsightlyPHP\ObjectSerializer;

/**
 * ProjectsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProjectsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addActivitySetAssignment
     *
     * Adds an Activity Set to a Project.
     *
     */
    public function testAddActivitySetAssignment()
    {
    }

    /**
     * Test case for addEntity
     *
     * Adds a Project.
     *
     */
    public function testAddEntity()
    {
    }

    /**
     * Test case for addFileAttachment
     *
     * Adds a File Attachment to a Project.
     *
     */
    public function testAddFileAttachment()
    {
    }

    /**
     * Test case for addFollow
     *
     * Start following a Project.
     *
     */
    public function testAddFollow()
    {
    }

    /**
     * Test case for addLink
     *
     * Adds a Link.
     *
     */
    public function testAddLink()
    {
    }

    /**
     * Test case for addMilestone
     *
     * Adds a Milestone.
     *
     */
    public function testAddMilestone()
    {
    }

    /**
     * Test case for addNotes
     *
     * Adds a Note to a Project.
     *
     */
    public function testAddNotes()
    {
    }

    /**
     * Test case for addTag
     *
     * Adds a Tag to a Project.
     *
     */
    public function testAddTag()
    {
    }

    /**
     * Test case for deleteEntity
     *
     * Deletes a Project.
     *
     */
    public function testDeleteEntity()
    {
    }

    /**
     * Test case for deleteFollow
     *
     * Stop following a Project.
     *
     */
    public function testDeleteFollow()
    {
    }

    /**
     * Test case for deleteImage
     *
     * Deletes a Project's Image.
     *
     */
    public function testDeleteImage()
    {
    }

    /**
     * Test case for deleteImageField
     *
     * Deletes a Project's Custom Image Field.
     *
     */
    public function testDeleteImageField()
    {
    }

    /**
     * Test case for deleteLink
     *
     * Deletes a Link.
     *
     */
    public function testDeleteLink()
    {
    }

    /**
     * Test case for deleteMilestone
     *
     * Deletes a Milestone.
     *
     */
    public function testDeleteMilestone()
    {
    }

    /**
     * Test case for deletePipeline
     *
     * Clears pipeline for the Project.
     *
     */
    public function testDeletePipeline()
    {
    }

    /**
     * Test case for deleteTag
     *
     * Deletes a Tag from a Project.
     *
     */
    public function testDeleteTag()
    {
    }

    /**
     * Test case for getEmails
     *
     * Gets a list of a Project's Emails.
     *
     */
    public function testGetEmails()
    {
    }

    /**
     * Test case for getEntities
     *
     * Gets a list of Projects.
     *
     */
    public function testGetEntities()
    {
    }

    /**
     * Test case for getEntitiesBySearch
     *
     * Gets a filtered list of Projects.
     *
     */
    public function testGetEntitiesBySearch()
    {
    }

    /**
     * Test case for getEntitiesByTag
     *
     * Gets a list of Projects filtered by tags.
     *
     */
    public function testGetEntitiesByTag()
    {
    }

    /**
     * Test case for getEntity
     *
     * Gets a Project.
     *
     */
    public function testGetEntity()
    {
    }

    /**
     * Test case for getEvents
     *
     * Gets a Project's Events.
     *
     */
    public function testGetEvents()
    {
    }

    /**
     * Test case for getFileAttachments
     *
     * Gets a Project's File Attachments.
     *
     */
    public function testGetFileAttachments()
    {
    }

    /**
     * Test case for getFollow
     *
     * Gets a Follow state for a Project.
     *
     */
    public function testGetFollow()
    {
    }

    /**
     * Test case for getImage
     *
     * Gets a Project's Image.
     *
     */
    public function testGetImage()
    {
    }

    /**
     * Test case for getImageField
     *
     * Gets a Project's Custom Image Field.
     *
     */
    public function testGetImageField()
    {
    }

    /**
     * Test case for getLinkEmailAddress
     *
     * Gets the email address to use for linking with the Project.
     *
     */
    public function testGetLinkEmailAddress()
    {
    }

    /**
     * Test case for getLinks
     *
     * Gets a Project's Links.
     *
     */
    public function testGetLinks()
    {
    }

    /**
     * Test case for getMilestones
     *
     * Gets a list of a Project's Milestones.
     *
     */
    public function testGetMilestones()
    {
    }

    /**
     * Test case for getNotes
     *
     * Gets a Project's Notes.
     *
     */
    public function testGetNotes()
    {
    }

    /**
     * Test case for getTags
     *
     * Gets a Project's Tags.
     *
     */
    public function testGetTags()
    {
    }

    /**
     * Test case for getTasks
     *
     * Gets a list of a Project's Tasks.
     *
     */
    public function testGetTasks()
    {
    }

    /**
     * Test case for updateEntity
     *
     * Updates a Project.
     *
     */
    public function testUpdateEntity()
    {
    }

    /**
     * Test case for updateImage
     *
     * Updates a Project's Image.
     *
     */
    public function testUpdateImage()
    {
    }

    /**
     * Test case for updateImageField
     *
     * Updates a Project's Custom Image Field.
     *
     */
    public function testUpdateImageField()
    {
    }

    /**
     * Test case for updateLink
     *
     * Updates a Link.
     *
     */
    public function testUpdateLink()
    {
    }

    /**
     * Test case for updateMilestone
     *
     * Updates a Milestone.
     *
     */
    public function testUpdateMilestone()
    {
    }

    /**
     * Test case for updateNotes
     *
     * Updates a note of a Project.
     *
     */
    public function testUpdateNotes()
    {
    }

    /**
     * Test case for updatePipeline
     *
     * Changes current pipeline for the Project.
     *
     */
    public function testUpdatePipeline()
    {
    }

    /**
     * Test case for updatePipelineStage
     *
     * Changes current pipeline stage for the Project.
     *
     */
    public function testUpdatePipelineStage()
    {
    }

    /**
     * Test case for updateTags
     *
     * Updates a Project's Tags.
     *
     */
    public function testUpdateTags()
    {
    }
}
