<?php
/**
 * ProspectsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SternerStuff\InsightlyPHP;

use \SternerStuff\InsightlyPHP\Configuration;
use \SternerStuff\InsightlyPHP\ApiException;
use \SternerStuff\InsightlyPHP\ObjectSerializer;

/**
 * ProspectsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProspectsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addEntity
     *
     * Adds a Prospect.
     *
     */
    public function testAddEntity()
    {
    }

    /**
     * Test case for addFollow
     *
     * Start following a Prospect.
     *
     */
    public function testAddFollow()
    {
    }

    /**
     * Test case for addTag
     *
     * Adds a Tag to a Prospect.
     *
     */
    public function testAddTag()
    {
    }

    /**
     * Test case for deleteEntity
     *
     * Deletes a Prospect.
     *
     */
    public function testDeleteEntity()
    {
    }

    /**
     * Test case for deleteFollow
     *
     * Stop following a Prospect.
     *
     */
    public function testDeleteFollow()
    {
    }

    /**
     * Test case for deleteImageField
     *
     * Deletes a Prospect's Custom Image Field.
     *
     */
    public function testDeleteImageField()
    {
    }

    /**
     * Test case for deleteTag
     *
     * Deletes a Tag from a Prospect.
     *
     */
    public function testDeleteTag()
    {
    }

    /**
     * Test case for getEntities
     *
     * Gets a list of Prospects.
     *
     */
    public function testGetEntities()
    {
    }

    /**
     * Test case for getEntitiesBySearch
     *
     * Gets a filtered list of Prospects.
     *
     */
    public function testGetEntitiesBySearch()
    {
    }

    /**
     * Test case for getEntitiesByTag
     *
     * Gets a list of Prospects filtered by tags.
     *
     */
    public function testGetEntitiesByTag()
    {
    }

    /**
     * Test case for getEntity
     *
     * Gets a Prospect.
     *
     */
    public function testGetEntity()
    {
    }

    /**
     * Test case for getFollow
     *
     * Gets a Follow state for a Prospect.
     *
     */
    public function testGetFollow()
    {
    }

    /**
     * Test case for getImageField
     *
     * Gets a Prospect's Custom Image Field.
     *
     */
    public function testGetImageField()
    {
    }

    /**
     * Test case for getTags
     *
     * Gets a Prospect's Tags.
     *
     */
    public function testGetTags()
    {
    }

    /**
     * Test case for updateEntity
     *
     * Updates a Prospect.
     *
     */
    public function testUpdateEntity()
    {
    }

    /**
     * Test case for updateImageField
     *
     * Updates a Prospect's Custom Image Field.
     *
     */
    public function testUpdateImageField()
    {
    }

    /**
     * Test case for updateTags
     *
     * Updates a Prospect's Tags.
     *
     */
    public function testUpdateTags()
    {
    }
}
