<?php
/**
 * QuotesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SternerStuff\InsightlyPHP;

use \SternerStuff\InsightlyPHP\Configuration;
use \SternerStuff\InsightlyPHP\ApiException;
use \SternerStuff\InsightlyPHP\ObjectSerializer;

/**
 * QuotesApiTest Class Doc Comment
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QuotesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addChildEntity
     *
     * Adds a Quote Product to a Quote.
     *
     */
    public function testAddChildEntity()
    {
    }

    /**
     * Test case for addEntity
     *
     * Adds a Quote.
     *
     */
    public function testAddEntity()
    {
    }

    /**
     * Test case for addFollow
     *
     * Start following a Quote.
     *
     */
    public function testAddFollow()
    {
    }

    /**
     * Test case for deleteChildEntity
     *
     * Deletes a Quote Document of a Quote.
     *
     */
    public function testDeleteChildEntity()
    {
    }

    /**
     * Test case for deleteChildEntity_0
     *
     * Deletes a Quote Product of a Quote.
     *
     */
    public function testDeleteChildEntity0()
    {
    }

    /**
     * Test case for deleteEntity
     *
     * Deletes a Quote.
     *
     */
    public function testDeleteEntity()
    {
    }

    /**
     * Test case for deleteFollow
     *
     * Stop following a Quote.
     *
     */
    public function testDeleteFollow()
    {
    }

    /**
     * Test case for deleteImageField
     *
     * Deletes a Quote's Custom Image Field.
     *
     */
    public function testDeleteImageField()
    {
    }

    /**
     * Test case for getChildEntities
     *
     * Gets a list of Quote Documents of a Quote.
     *
     */
    public function testGetChildEntities()
    {
    }

    /**
     * Test case for getChildEntities_0
     *
     * Gets a list of Quote Products of a Quote.
     *
     */
    public function testGetChildEntities0()
    {
    }

    /**
     * Test case for getEntities
     *
     * Gets a list of Quotes.
     *
     */
    public function testGetEntities()
    {
    }

    /**
     * Test case for getEntitiesBySearch
     *
     * Gets a filtered list of Quotes.
     *
     */
    public function testGetEntitiesBySearch()
    {
    }

    /**
     * Test case for getEntity
     *
     * Gets a Quote.
     *
     */
    public function testGetEntity()
    {
    }

    /**
     * Test case for getFollow
     *
     * Gets a Follow state for a Quote.
     *
     */
    public function testGetFollow()
    {
    }

    /**
     * Test case for getImageField
     *
     * Gets a Quote's Custom Image Field.
     *
     */
    public function testGetImageField()
    {
    }

    /**
     * Test case for updateChildEntity
     *
     * Updates a Quote Product of a Quote.
     *
     */
    public function testUpdateChildEntity()
    {
    }

    /**
     * Test case for updateEntity
     *
     * Updates a Quote.
     *
     */
    public function testUpdateEntity()
    {
    }

    /**
     * Test case for updateImageField
     *
     * Updates a Quote's Custom Image Field.
     *
     */
    public function testUpdateImageField()
    {
    }
}
