<?php
/**
 * TasksApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v3.1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SternerStuff\InsightlyPHP;

use \SternerStuff\InsightlyPHP\Configuration;
use \SternerStuff\InsightlyPHP\ApiException;
use \SternerStuff\InsightlyPHP\ObjectSerializer;

/**
 * TasksApiTest Class Doc Comment
 *
 * @category Class
 * @package  SternerStuff\InsightlyPHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TasksApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addComment
     *
     * Adds a Comment to a Task.
     *
     */
    public function testAddComment()
    {
    }

    /**
     * Test case for addEntity
     *
     * Adds a Task.
     *
     */
    public function testAddEntity()
    {
    }

    /**
     * Test case for addFollow
     *
     * Start following a Task.
     *
     */
    public function testAddFollow()
    {
    }

    /**
     * Test case for addLink
     *
     * Adds a Link.
     *
     */
    public function testAddLink()
    {
    }

    /**
     * Test case for deleteEntity
     *
     * Deletes a Task.
     *
     */
    public function testDeleteEntity()
    {
    }

    /**
     * Test case for deleteFollow
     *
     * Stop following a Task.
     *
     */
    public function testDeleteFollow()
    {
    }

    /**
     * Test case for deleteImageField
     *
     * Deletes a Task's Custom Image Field.
     *
     */
    public function testDeleteImageField()
    {
    }

    /**
     * Test case for deleteLink
     *
     * Deletes a Link.
     *
     */
    public function testDeleteLink()
    {
    }

    /**
     * Test case for getComments
     *
     * Gets a Task's Comments.
     *
     */
    public function testGetComments()
    {
    }

    /**
     * Test case for getEntities
     *
     * Gets a list of Tasks.
     *
     */
    public function testGetEntities()
    {
    }

    /**
     * Test case for getEntitiesBySearch
     *
     * Gets a filtered list of Tasks.
     *
     */
    public function testGetEntitiesBySearch()
    {
    }

    /**
     * Test case for getEntity
     *
     * Gets a Task.
     *
     */
    public function testGetEntity()
    {
    }

    /**
     * Test case for getFollow
     *
     * Gets a Follow state for a Task.
     *
     */
    public function testGetFollow()
    {
    }

    /**
     * Test case for getImageField
     *
     * Gets a Task's Custom Image Field.
     *
     */
    public function testGetImageField()
    {
    }

    /**
     * Test case for getLinks
     *
     * Gets a Task's Links.
     *
     */
    public function testGetLinks()
    {
    }

    /**
     * Test case for updateEntity
     *
     * Updates a Task.
     *
     */
    public function testUpdateEntity()
    {
    }

    /**
     * Test case for updateImageField
     *
     * Updates a Task's Custom Image Field.
     *
     */
    public function testUpdateImageField()
    {
    }
}
